name: BeatBlocks
main: me.xtreme727.beatblocks.BeatBlocks
version: 0.0.1
author: Xtreme727
api-version: '1.21'

commands:
  beatblocks:
    description: Core command
    usage: /beatblocks <arguments>